import type {
  LeafNodeIdAlt,
  RegistrationGoalAlt,
  RegistrationVenue,
} from "@/types/submit-alt"

// 36 leaf の各種マスタ。docs/submit-alt.md 参照。

// 仕様書の番号 ID（leaf-NN / v01-v03 / m06 / s01-s02）
export const LEAF_LEGACY_ID: Readonly<Record<LeafNodeIdAlt, string>> = {
  "human-restricted": "leaf-01",
  "proteomics": "leaf-02",
  "metabolomics": "leaf-03",
  "variation-nonhuman": "v01",
  "variation-human-open": "v02",
  "variation-human-restricted": "v03",
  "expression-ngs": "leaf-08",
  "expression-array": "leaf-09",
  "small-sequence": "leaf-10",
  "metagenome-raw": "leaf-11",
  "metagenome-primary": "leaf-12",
  "metagenome-genome-bin": "leaf-13",
  "metagenome-tls": "leaf-14",
  "metagenome-tsa": "leaf-15",
  "human-microbiome-restricted": "m06",
  "organelle-plasmid": "leaf-16",
  "prokaryote-raw": "leaf-17",
  "prokaryote-raw-assembly": "leaf-18",
  "prokaryote-assembly-only": "leaf-19",
  "virus-raw": "leaf-20",
  "virus-raw-assembly": "leaf-21",
  "virus-assembly-only": "leaf-22",
  "eukaryote-tsa": "leaf-23",
  "eukaryote-tpa": "leaf-24",
  "eukaryote-raw": "leaf-25",
  "eukaryote-raw-assembly": "leaf-26",
  "eukaryote-assembly-only": "leaf-27",
  "eukaryote-haplotype-raw-assembly": "leaf-28",
  "eukaryote-haplotype-assembly-only": "leaf-29",
  "eukaryote-est-small": "leaf-30",
  "eukaryote-est-large": "leaf-31",
  "spatial-tx-nonhuman": "s01",
  "spatial-tx-restricted": "s02",
  "human-raw-open": "leaf-32",
  "human-raw-assembly-open": "leaf-33",
  "human-assembly-only-open": "leaf-34",
}

export const LEAF_GOALS_ALT: Readonly<Record<LeafNodeIdAlt, RegistrationGoalAlt>> = {
  "human-restricted": "JGA",
  "proteomics": "jPOST",
  "metabolomics": "BP+BS+MetaboBank",
  "variation-nonhuman": "EVA",
  "variation-human-open": "JVar SNP",
  "variation-human-restricted": "JGA-analysis",
  "expression-ngs": "BP+BS+DRA+GEA",
  "expression-array": "BP+BS+GEA",
  "small-sequence": "NSSS",
  "metagenome-raw": "BP+BS+DRA",
  "metagenome-primary": "BP+BS+DRA(Analysis)",
  "metagenome-genome-bin": "BP+BS+DRA+MSS",
  "metagenome-tls": "BP+BS+DRA+MSS(TLS)",
  "metagenome-tsa": "BP+BS+DRA+MSS(TSA)",
  "human-microbiome-restricted": "JGA-analysis",
  "organelle-plasmid": "BP+BS+MSS",
  "prokaryote-raw": "BP+BS+DRA",
  "prokaryote-raw-assembly": "BP+BS+DRA+MSS",
  "prokaryote-assembly-only": "BP+BS+MSS",
  "virus-raw": "BP+BS+DRA",
  "virus-raw-assembly": "BP+BS+DRA+MSS",
  "virus-assembly-only": "BP+BS+MSS",
  "eukaryote-tsa": "BP+BS+DRA+MSS(TSA)",
  "eukaryote-tpa": "BP+BS+MSS(TPA)",
  "eukaryote-raw": "BP+BS+DRA",
  "eukaryote-raw-assembly": "BP+BS+DRA+MSS",
  "eukaryote-assembly-only": "BP+BS+MSS",
  "eukaryote-haplotype-raw-assembly": "BP+BS+DRA+MSS(Haplotype)",
  "eukaryote-haplotype-assembly-only": "BP+BS+MSS(Haplotype)",
  "eukaryote-est-small": "NSSS(EST)",
  "eukaryote-est-large": "BP+BS+MSS(EST)",
  "spatial-tx-nonhuman": "BP+BS+GEA(Xenium)",
  "spatial-tx-restricted": "JGA-analysis",
  "human-raw-open": "BP+BS+DRA",
  "human-raw-assembly-open": "BP+BS+DRA+MSS",
  "human-assembly-only-open": "BP+BS+MSS",
}

// 内部 (BSI/DDBJ 内部) / 外部 (jPOST / EVA / dgVa / HumanDBs)
export const LEAF_VENUE_ALT: Readonly<Record<LeafNodeIdAlt, RegistrationVenue>> = {
  "human-restricted": "internal",
  "proteomics": "external",
  "metabolomics": "internal",
  "variation-nonhuman": "external",
  "variation-human-open": "internal",
  "variation-human-restricted": "internal",
  "expression-ngs": "internal",
  "expression-array": "internal",
  "small-sequence": "internal",
  "metagenome-raw": "internal",
  "metagenome-primary": "internal",
  "metagenome-genome-bin": "internal",
  "metagenome-tls": "internal",
  "metagenome-tsa": "internal",
  "human-microbiome-restricted": "internal",
  "organelle-plasmid": "internal",
  "prokaryote-raw": "internal",
  "prokaryote-raw-assembly": "internal",
  "prokaryote-assembly-only": "internal",
  "virus-raw": "internal",
  "virus-raw-assembly": "internal",
  "virus-assembly-only": "internal",
  "eukaryote-tsa": "internal",
  "eukaryote-tpa": "internal",
  "eukaryote-raw": "internal",
  "eukaryote-raw-assembly": "internal",
  "eukaryote-assembly-only": "internal",
  "eukaryote-haplotype-raw-assembly": "internal",
  "eukaryote-haplotype-assembly-only": "internal",
  "eukaryote-est-small": "internal",
  "eukaryote-est-large": "internal",
  "spatial-tx-nonhuman": "internal",
  "spatial-tx-restricted": "internal",
  "human-raw-open": "internal",
  "human-raw-assembly-open": "internal",
  "human-assembly-only-open": "internal",
}

// 候補リスト表示で使う leaf のラベルキー。i18n の routes.submitAlt.tree.options.* と
// routes.submitAlt.dataTypes.*.label / routes.submitAlt.leaves.*.label を参照する。
export const LEAF_LABEL_KEY_ALT: Readonly<Record<LeafNodeIdAlt, string>> = {
  "human-restricted": "routes.submitAlt.dataTypes.human-restricted.label",
  "proteomics": "routes.submitAlt.dataTypes.proteomics.label",
  "metabolomics": "routes.submitAlt.dataTypes.metabolomics.label",
  "small-sequence": "routes.submitAlt.dataTypes.small-sequence.label",
  "expression-array": "routes.submitAlt.dataTypes.microarray.label",
  "variation-nonhuman": "routes.submitAlt.tree.options.variation.nonhuman",
  "variation-human-open": "routes.submitAlt.tree.options.variation.human-open",
  "variation-human-restricted": "routes.submitAlt.tree.options.variation.human-restricted",
  "spatial-tx-nonhuman": "routes.submitAlt.tree.options.spatial-transcriptomics.nonhuman",
  "spatial-tx-restricted": "routes.submitAlt.tree.options.spatial-transcriptomics.restricted",
  "expression-ngs": "routes.submitAlt.tree.options.sequence-read.expression-ngs",
  "eukaryote-est-small": "routes.submitAlt.tree.options.est.small",
  "eukaryote-est-large": "routes.submitAlt.tree.options.est.large",
  "metagenome-raw": "routes.submitAlt.tree.options.sequence-read-metagenome.raw",
  "metagenome-primary": "routes.submitAlt.tree.options.sequence-read-metagenome.primary",
  "metagenome-genome-bin": "routes.submitAlt.tree.options.genome-metagenome.genome-bin",
  "metagenome-tls": "routes.submitAlt.tree.options.genome-metagenome.tls",
  "metagenome-tsa": "routes.submitAlt.tree.options.genome-metagenome.tsa",
  "human-microbiome-restricted": "routes.submitAlt.tree.options.genome-metagenome.human-restricted",
  "organelle-plasmid": "routes.submitAlt.tree.options.genome.organelle-plasmid",
  "prokaryote-raw": "routes.submitAlt.tree.options.sequence-read.prokaryote-raw",
  "prokaryote-raw-assembly": "routes.submitAlt.tree.options.genome-prokaryote.raw-assembly",
  "prokaryote-assembly-only": "routes.submitAlt.tree.options.genome-prokaryote.assembly-only",
  "virus-raw": "routes.submitAlt.tree.options.sequence-read.virus-raw",
  "virus-raw-assembly": "routes.submitAlt.tree.options.genome-virus.raw-assembly",
  "virus-assembly-only": "routes.submitAlt.tree.options.genome-virus.assembly-only",
  "eukaryote-tsa": "routes.submitAlt.tree.options.genome-eukaryote.tsa",
  "eukaryote-tpa": "routes.submitAlt.tree.options.genome-eukaryote.tpa",
  "eukaryote-raw": "routes.submitAlt.tree.options.sequence-read.eukaryote-raw",
  "eukaryote-raw-assembly": "routes.submitAlt.tree.options.genome-eukaryote.raw-assembly",
  "eukaryote-assembly-only": "routes.submitAlt.tree.options.genome-eukaryote.assembly-only",
  "eukaryote-haplotype-raw-assembly": "routes.submitAlt.tree.options.genome-eukaryote.haplotype-raw-assembly",
  "eukaryote-haplotype-assembly-only": "routes.submitAlt.tree.options.genome-eukaryote.haplotype-assembly-only",
  "human-raw-open": "routes.submitAlt.leaves.human-raw-open.label",
  "human-raw-assembly-open": "routes.submitAlt.leaves.human-raw-assembly-open.label",
  "human-assembly-only-open": "routes.submitAlt.leaves.human-assembly-only-open.label",
}

