import type { UseCaseCardAlt } from "@/types/submit-alt"

// docs/submit-alt.md L97-110 参照。10 枚（旧 9 枚 + 空間 Tx 新設）。
// 表示順: ゲノム系を先頭、ヒト制限アクセスを最後（属性カード扱い）。
export const USE_CASE_CARDS_ALT = [
  {
    id: "microbial-genome",
    titleKey: "routes.submitAlt.cards.microbial-genome.title",
    descriptionKey: "routes.submitAlt.cards.microbial-genome.description",
    iconName: "Bug",
    treeNodeId: "genome",
    relatedDataTypes: ["genome", "sequence-read"],
    relatedLeafIds: [
      "organelle-plasmid",
      "prokaryote-raw",
      "prokaryote-raw-assembly",
      "prokaryote-assembly-only",
      "virus-raw",
      "virus-raw-assembly",
      "virus-assembly-only",
    ],
    order: 1,
  },
  {
    id: "eukaryote-genome",
    titleKey: "routes.submitAlt.cards.eukaryote-genome.title",
    descriptionKey: "routes.submitAlt.cards.eukaryote-genome.description",
    iconName: "Trees",
    treeNodeId: "genome",
    relatedDataTypes: ["genome", "sequence-read", "est"],
    relatedLeafIds: [
      "eukaryote-tsa",
      "eukaryote-tpa",
      "eukaryote-raw",
      "eukaryote-raw-assembly",
      "eukaryote-assembly-only",
      "eukaryote-haplotype-raw-assembly",
      "eukaryote-haplotype-assembly-only",
      "eukaryote-est-small",
      "eukaryote-est-large",
    ],
    order: 2,
  },
  {
    id: "metagenome",
    titleKey: "routes.submitAlt.cards.metagenome.title",
    descriptionKey: "routes.submitAlt.cards.metagenome.description",
    iconName: "Microscope",
    treeNodeId: "genome-metagenome",
    relatedDataTypes: ["sequence-read", "genome", "human-restricted"],
    relatedLeafIds: [
      "metagenome-raw",
      "metagenome-primary",
      "metagenome-genome-bin",
      "metagenome-tls",
      "metagenome-tsa",
      "human-microbiome-restricted",
    ],
    order: 3,
  },
  {
    id: "expression",
    titleKey: "routes.submitAlt.cards.expression.title",
    descriptionKey: "routes.submitAlt.cards.expression.description",
    iconName: "BarChart3",
    treeNodeId: "expression-ngs",
    relatedDataTypes: ["sequence-read", "microarray"],
    relatedLeafIds: ["expression-ngs", "expression-array"],
    order: 4,
  },
  {
    id: "spatial-tx",
    titleKey: "routes.submitAlt.cards.spatial-tx.title",
    descriptionKey: "routes.submitAlt.cards.spatial-tx.description",
    iconName: "LayoutGrid",
    treeNodeId: "spatial-transcriptomics",
    relatedDataTypes: ["spatial-transcriptomics", "human-restricted"],
    relatedLeafIds: ["spatial-tx-nonhuman", "spatial-tx-restricted"],
    order: 5,
  },
  {
    id: "variation",
    titleKey: "routes.submitAlt.cards.variation.title",
    descriptionKey: "routes.submitAlt.cards.variation.description",
    iconName: "GitBranch",
    treeNodeId: "variation",
    relatedDataTypes: ["variation", "human-restricted"],
    relatedLeafIds: [
      "variation-nonhuman",
      "variation-human-open",
      "variation-human-restricted",
    ],
    order: 6,
  },
  {
    id: "proteomics",
    titleKey: "routes.submitAlt.cards.proteomics.title",
    descriptionKey: "routes.submitAlt.cards.proteomics.description",
    iconName: "FlaskConical",
    treeNodeId: "proteomics",
    relatedDataTypes: ["proteomics"],
    relatedLeafIds: ["proteomics"],
    order: 7,
  },
  {
    id: "metabolomics",
    titleKey: "routes.submitAlt.cards.metabolomics.title",
    descriptionKey: "routes.submitAlt.cards.metabolomics.description",
    iconName: "TestTube",
    treeNodeId: "metabolomics",
    relatedDataTypes: ["metabolomics"],
    relatedLeafIds: ["metabolomics"],
    order: 8,
  },
  {
    id: "small-sequence",
    titleKey: "routes.submitAlt.cards.small-sequence.title",
    descriptionKey: "routes.submitAlt.cards.small-sequence.description",
    iconName: "FileText",
    treeNodeId: "small-sequence",
    relatedDataTypes: ["small-sequence"],
    relatedLeafIds: ["small-sequence"],
    order: 9,
  },
  {
    id: "human-restricted",
    titleKey: "routes.submitAlt.cards.human-restricted.title",
    descriptionKey: "routes.submitAlt.cards.human-restricted.description",
    iconName: "Lock",
    treeNodeId: "human-restricted",
    relatedDataTypes: ["human-restricted"],
    relatedLeafIds: ["human-restricted"],
    order: 10,
  },
] as const satisfies readonly UseCaseCardAlt[]

export const isCardRelevant = (
  card: UseCaseCardAlt,
  types: ReadonlySet<UseCaseCardAlt["relatedDataTypes"][number]>,
): boolean => {
  if (types.size === 0) return false

  return card.relatedDataTypes.some((dt) => types.has(dt))
}
