import type { UseCaseCard } from "@/types/submit"

// docs/submit.md L307-321 の表に整合。i18n キーは locales/{ja,en}.json で解決。
export const USE_CASE_CARDS = [
  {
    id: "microbial",
    titleKey: "routes.submit.cards.microbial.title",
    descriptionKey: "routes.submit.cards.microbial.description",
    iconName: "Bug",
    treeNodeId: "microbial",
    order: 1,
    leafCount: 7,
  },
  {
    id: "eukaryote",
    titleKey: "routes.submit.cards.eukaryote.title",
    descriptionKey: "routes.submit.cards.eukaryote.description",
    iconName: "Trees",
    treeNodeId: "eukaryote",
    order: 2,
    leafCount: 9,
  },
  {
    id: "metagenome",
    titleKey: "routes.submit.cards.metagenome.title",
    descriptionKey: "routes.submit.cards.metagenome.description",
    iconName: "Microscope",
    treeNodeId: "metagenome",
    order: 3,
    leafCount: 5,
  },
  {
    id: "expression",
    titleKey: "routes.submit.cards.expression.title",
    descriptionKey: "routes.submit.cards.expression.description",
    iconName: "BarChart3",
    treeNodeId: "expression",
    order: 4,
    leafCount: 2,
  },
  {
    id: "variation",
    titleKey: "routes.submit.cards.variation.title",
    descriptionKey: "routes.submit.cards.variation.description",
    iconName: "GitBranch",
    treeNodeId: "variation",
    order: 5,
    leafCount: 4,
  },
  {
    id: "proteomics",
    titleKey: "routes.submit.cards.proteomics.title",
    descriptionKey: "routes.submit.cards.proteomics.description",
    iconName: "FlaskConical",
    treeNodeId: "proteomics",
    order: 6,
    leafCount: 1,
  },
  {
    id: "metabolomics",
    titleKey: "routes.submit.cards.metabolomics.title",
    descriptionKey: "routes.submit.cards.metabolomics.description",
    iconName: "TestTube",
    treeNodeId: "metabolomics",
    order: 7,
    leafCount: 1,
  },
  {
    id: "small-sequence",
    titleKey: "routes.submit.cards.small-sequence.title",
    descriptionKey: "routes.submit.cards.small-sequence.description",
    iconName: "FileText",
    treeNodeId: "small-sequence",
    order: 8,
    leafCount: 1,
  },
  {
    id: "human-restricted",
    titleKey: "routes.submit.cards.human-restricted.title",
    descriptionKey: "routes.submit.cards.human-restricted.description",
    iconName: "Lock",
    treeNodeId: "human-restricted",
    order: 9,
    leafCount: 1,
  },
] as const satisfies readonly UseCaseCard[]
