import type { UseCaseCard } from "@/types/submit"

// docs/submit.md L307-321 の表に整合
export const USE_CASE_CARDS = [
  {
    id: "microbial",
    title: "微生物ゲノム",
    description: "原核生物・ウイルス・オルガネラ・プラスミドのゲノム登録",
    iconName: "Bug",
    treeNodeId: "microbial",
    order: 1,
    leafCount: 7,
  },
  {
    id: "eukaryote",
    title: "真核生物ゲノム",
    description: "動物・植物・菌類のゲノム登録（Haplotype / TSA / EST / TPA 含む）",
    iconName: "Trees",
    treeNodeId: "eukaryote",
    order: 2,
    leafCount: 9,
  },
  {
    id: "metagenome",
    title: "メタゲノム / MAG / SAG",
    description: "環境サンプル・メタゲノム由来データ",
    iconName: "Microscope",
    treeNodeId: "metagenome",
    order: 3,
    leafCount: 5,
  },
  {
    id: "expression",
    title: "遺伝子発現",
    description: "RNA-seq・マイクロアレイ等の発現解析データ",
    iconName: "BarChart3",
    treeNodeId: "expression",
    order: 4,
    leafCount: 2,
  },
  {
    id: "variation",
    title: "変異データ",
    description: "SNP / 構造変異等の変異コール結果",
    iconName: "GitBranch",
    treeNodeId: "variation",
    order: 5,
    leafCount: 4,
  },
  {
    id: "proteomics",
    title: "プロテオミクス",
    description: "LC-MS/MS によるプロテオーム解析データ（jPOST 経由）",
    iconName: "FlaskConical",
    treeNodeId: "proteomics",
    order: 6,
    leafCount: 1,
  },
  {
    id: "metabolomics",
    title: "メタボロミクス",
    description: "LC-MS / GC-MS 等のメタボロミクスデータ",
    iconName: "TestTube",
    treeNodeId: "metabolomics",
    order: 7,
    leafCount: 1,
  },
  {
    id: "small-sequence",
    title: "小規模塩基配列・PCR 産物",
    description: "100 配列未満の塩基配列（NSSS 経由）",
    iconName: "FileText",
    treeNodeId: "small-sequence",
    order: 8,
    leafCount: 1,
  },
  {
    id: "human-restricted",
    title: "ヒト制限アクセス",
    description: "ヒトを対象とした個人特定リスクのあるデータ（NBDC 承認要）",
    iconName: "Lock",
    treeNodeId: "human-restricted",
    order: 9,
    leafCount: 1,
  },
] as const satisfies readonly UseCaseCard[]
