import type { DatabaseContent } from "~/schemas/content/database-content"
import { Callout, Heading, TextLink } from "~/ui"

import { SubmitGuideSection } from "../submit-guide-section"

export default {
  slug: "dra",
  title: {
    ja: "DRA (DDBJ Sequence Read Archive)",
    en: "DRA (DDBJ Sequence Read Archive)",
  },
  description: {
    ja: "次世代シーケンサーから出力される配列リード（FASTQ / BAM 等）のアーカイブ。INSDC の SRA と相互共有される。",
    en: "Archive for sequence reads (FASTQ / BAM etc.) generated by next-generation sequencers. Shared internationally via INSDC SRA.",
  },
  body: {
    ja: (
      <div className="flex flex-col gap-section-md">
        <section>
          <Heading as="h2" bar className="mb-3">DRA とは</Heading>
          <p className="text-fs-body text-ink-mid leading-relaxed m-0">
            DDBJ Sequence Read Archive (DRA) は、次世代シーケンサーから出力される配列データを受け付ける公開アーカイブです。
            FASTQ や BAM 形式のリードファイルに加え、実験メタデータ (Experiment / Run) を登録します。
            登録データは INSDC パートナー (NCBI SRA / EBI ENA) と継続的に交換されます。
          </p>
        </section>
        <SubmitGuideSection service="dra" lang="ja" />
        <Callout tone="info">
          <TextLink to="/submit">登録ナビ</TextLink>
          {" "}
          で配列リードを選ぶと、BioProject・BioSample・DRA の登録経路が自動で組み立てられます。
        </Callout>
      </div>
    ),
    en: (
      <div className="flex flex-col gap-section-md">
        <section>
          <Heading as="h2" bar className="mb-3">About DRA</Heading>
          <p className="text-fs-body text-ink-mid leading-relaxed m-0">
            DDBJ Sequence Read Archive (DRA) is a public archive for sequence read data from
            next-generation sequencers. It accepts FASTQ and BAM read files along with experiment
            metadata (Experiment / Run). Submitted data is continuously exchanged with INSDC
            partners (NCBI SRA / EBI ENA).
          </p>
        </section>
        <SubmitGuideSection service="dra" lang="en" />
        <Callout tone="info">
          Choose &quot;sequence reads&quot; in the{" "}
          <TextLink to="/submit">submission navigator</TextLink>
          {" "}
          to see the BioProject → BioSample → DRA registration path assembled automatically.
        </Callout>
      </div>
    ),
  },
  meta: {
    lastUpdated: "2026-06-15T00:00:00Z",
    relatedDbs: ["bioproject", "biosample"],
    externalLinks: [
      { label: { ja: "DRA 公式ページ", en: "DRA official site" }, href: "https://www.ddbj.nig.ac.jp/dra/index.html" },
      { label: { ja: "NCBI SRA", en: "NCBI SRA" }, href: "https://www.ncbi.nlm.nih.gov/sra" },
      { label: { ja: "EBI ENA", en: "EBI ENA" }, href: "https://www.ebi.ac.uk/ena/browser/" },
    ],
  },
} satisfies DatabaseContent
