import type { LeafNodeId, RegistrationGoal } from "@/types/submit"

// docs/submit.md L207-224 のゴール一覧と整合
export const LEAF_GOALS: Readonly<Record<LeafNodeId, RegistrationGoal>> = {
  "human-restricted": "JGA",
  "proteomics": "jPOST",
  "metabolomics": "BP+BS+MetaboBank",
  "variation-human-snp": "JVar SNP",
  "variation-human-sv": "JVar SV",
  "variation-nonhuman-snp": "EVA",
  "variation-nonhuman-sv": "dgVa",
  "expression-ngs": "BP+BS+DRA+GEA",
  "expression-array": "BP+BS+GEA",
  "small-sequence": "NSSS",
  "metagenome-raw": "BP+BS+DRA",
  "metagenome-primary": "BP+BS+DRA (Analysis)",
  "metagenome-genome-bin": "BP+BS+DRA+MSS",
  "metagenome-tls": "BP+BS+DRA+MSS",
  "metagenome-tsa": "BP+BS+DRA+MSS",
  "organelle-plasmid": "BP+BS+MSS",
  "prokaryote-raw": "BP+BS+DRA",
  "prokaryote-raw-assembly": "BP+BS+DRA+MSS",
  "prokaryote-assembly-only": "BP+BS+MSS",
  "virus-raw": "BP+BS+DRA",
  "virus-raw-assembly": "BP+BS+DRA+MSS",
  "virus-assembly-only": "BP+BS+MSS",
  "eukaryote-tsa": "BP+BS+DRA+MSS",
  "eukaryote-tpa": "BP+BS+MSS",
  "eukaryote-raw": "BP+BS+DRA",
  "eukaryote-raw-assembly": "BP+BS+DRA+MSS",
  "eukaryote-assembly-only": "BP+BS+MSS",
  "eukaryote-haplotype-raw-assembly": "BP+BS+DRA+MSS (Haplotype)",
  "eukaryote-haplotype-assembly-only": "BP+BS+MSS (Haplotype)",
  "eukaryote-est-small": "NSSS",
  "eukaryote-est-large": "BP+BS+MSS",
}

export const LEAF_NUMBER: Readonly<Record<LeafNodeId, number>> = {
  "human-restricted": 1,
  "proteomics": 2,
  "metabolomics": 3,
  "variation-human-snp": 4,
  "variation-human-sv": 5,
  "variation-nonhuman-snp": 6,
  "variation-nonhuman-sv": 7,
  "expression-ngs": 8,
  "expression-array": 9,
  "small-sequence": 10,
  "metagenome-raw": 11,
  "metagenome-primary": 12,
  "metagenome-genome-bin": 13,
  "metagenome-tls": 14,
  "metagenome-tsa": 15,
  "organelle-plasmid": 16,
  "prokaryote-raw": 17,
  "prokaryote-raw-assembly": 18,
  "prokaryote-assembly-only": 19,
  "virus-raw": 20,
  "virus-raw-assembly": 21,
  "virus-assembly-only": 22,
  "eukaryote-tsa": 23,
  "eukaryote-tpa": 24,
  "eukaryote-raw": 25,
  "eukaryote-raw-assembly": 26,
  "eukaryote-assembly-only": 27,
  "eukaryote-haplotype-raw-assembly": 28,
  "eukaryote-haplotype-assembly-only": 29,
  "eukaryote-est-small": 30,
  "eukaryote-est-large": 31,
}

export const LEAF_PARENTS: Readonly<Record<LeafNodeId, string>> = {
  "human-restricted": "root",
  "proteomics": "modality",
  "metabolomics": "modality",
  "variation-human-snp": "variation",
  "variation-human-sv": "variation",
  "variation-nonhuman-snp": "variation",
  "variation-nonhuman-sv": "variation",
  "expression-ngs": "expression",
  "expression-array": "expression",
  "small-sequence": "sequence-scale",
  "metagenome-raw": "metagenome",
  "metagenome-primary": "metagenome",
  "metagenome-genome-bin": "metagenome",
  "metagenome-tls": "metagenome",
  "metagenome-tsa": "metagenome",
  "organelle-plasmid": "microbial",
  "prokaryote-raw": "prokaryote",
  "prokaryote-raw-assembly": "prokaryote",
  "prokaryote-assembly-only": "prokaryote",
  "virus-raw": "virus",
  "virus-raw-assembly": "virus",
  "virus-assembly-only": "virus",
  "eukaryote-tsa": "eukaryote",
  "eukaryote-tpa": "eukaryote",
  "eukaryote-raw": "eukaryote-genome",
  "eukaryote-raw-assembly": "eukaryote-genome",
  "eukaryote-assembly-only": "eukaryote-genome",
  "eukaryote-haplotype-raw-assembly": "eukaryote-haplotype",
  "eukaryote-haplotype-assembly-only": "eukaryote-haplotype",
  "eukaryote-est-small": "eukaryote-est",
  "eukaryote-est-large": "eukaryote-est",
}
