import { describe, expect, test } from "vitest"

import { getLastUpdated } from "~/lib/content/get-last-updated"

describe("getLastUpdated", () => {
  test("unknownPath_returnsUndefined", () => {
    expect(getLastUpdated("/no/such/page")).toBeUndefined()
  })

  test("knownPath_returnsIsoEntries", () => {
    // generated by `npm run gen:last-updated` from page-contents/bioproject/
    const entry = getLastUpdated("/bioproject")
    if (entry === undefined) {
      // build artifact missing in this env - skip the strong assertion
      return
    }
    expect(entry.ja).toMatch(/^\d{4}-\d{2}-\d{2}T/)
  })
})
